name: PR Check

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY_PJULIAN }}"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Analyzing the code with flake8
      run: |
        flake8 $(git ls-files '*.py')

  pylint:
    runs-on: ubuntu-latest
    needs: flake8 # pylint will only run after flake8 completes successfully
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY_PJULIAN }}"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Analyzing the code with pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')

  # pytest:
  #   runs-on: ubuntu-latest
  #   needs: pylint # pytest will only run after pylint completes successfully
  #   strategy:
  #     matrix:
  #       python-version: ["3.9", "3.10"]
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install dependencies
  #     env:
  #       SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  #     run: |
  #       mkdir -p ~/.ssh
  #       ssh-keyscan github.com >> ~/.ssh/known_hosts
  #       ssh-agent -a $SSH_AUTH_SOCK > /dev/null
  #       ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY_PJULIAN }}"
  #       echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install -r test-requirements.txt
  #   - name: Run unittests with pytest
  #     run: |
  #       pytest -v -s -n auto -l --cov=scripts --cov-report term-missing --cov-report xml --no-cov-on-fail tests/unit
